language: scala

jdk: oraclejdk8

scala:
   - 2.12.6

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
   - sbt ++$TRAVIS_SCALA_VERSION test
#   - sbt ++$TRAVIS_SCALA_VERSION scalastyle

notifications:
  email: false