version: '3.1'

services:
  tronexplorer:
    build:
      dockerfile: ./Dockerfile
      context: ./
    container_name: tron_explorer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ~/.ivy2:/root/.ivy2
      - ~/.sbt:/root/.sbt
  redis:
    image: redis:4.0
    restart: always
  pgsql:
    restart: always
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres